### ISSUE TITLE
Unable to load addon script - error in the code?

### ISSUE THREAD

**Issue by swein** [Jummit/Godot-Gravity-Objects#2]
Unable to load addon script from path: 'res://addons/Godot-Gravity-Objects-1.1/gravity_objects.gd' There seems to be an error in the code, please check the syntax.

SCRIPT ERROR: GDScript::reload: Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
          At: res://addons/Godot-Gravity-Objects-1.1/gravity_objects.gd:15
ERROR: reload: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:599

windows 10 - godot version 3.2.2

**Comment by Hyperjragon** [comment]
Me too. I couldnt find a fix, could you?

**Comment by Jummit** [comment]
Sorry for the late reply. This is because the plugin should be installed to `addons/gravity_objects`. Renaming the addon folder should make it work.

EDIT: fixed in 50cacfd1e2c0
